### ISSUE TITLE
可以一键导出api文档功能吗

### ISSUE THREAD

**Issue by snaigle** [terran4j/commons#1]
api2doc设计和效果很赞
我想可以导出所有的文档，单独对外提供一个静态服务，这样更方便也更安全
还有如果api详情页面可以添加api测试功能就更好了

thanks

**Comment by terran4j** [comment]
感谢你的肯定！
首先，导出所有文档功能，下一版会支持导出 html 格式及 md 格式，显示效果与目前一样。
另外，测试的功能，还在规划中，目前已经有很多 API 测试的项目，我希望做得与它们不一样。

**Comment by snaigle** [comment]
@terran4j  还是要以更有效率为第一目标， 与它们不一样的原因也是因为新设计更赞才行，为了不一样而改变反而会让项目变味

**Comment by liutf** [comment]
同求，等待中。

**Comment by qq1063410652** [comment]
从开始手写接口文档的时候，心里头就想自己写个。看了你这个感觉很棒，但是感觉注释比较少啊，，不知道现在能否生成doc文档？希望以后注释能都写上，因为暂时还没看太明白，以后也能帮忙出力
