### ISSUE TITLE
现在只解析RequestMapping，为什么不支持PostMapping？

### ISSUE THREAD

**Issue by fengcbo** [terran4j/commons#2]

**Comment by terran4j** [comment]
这个，下一版会支持，支持，包括：
    @GetMapping
    @PostMapping
    @PutMapping
    @DeleteMapping
    @PatchMapping
以及各个参数的支持，包括：
@RequestHeader
@CookieValue
@RequestPart
等。

**Comment by fengcbo** [comment]
下个版本有时间表吗？

**Comment by terran4j** [comment]
已发布 1.0.2 版本，支持这些功能，详细请访问：
https://github.com/terran4j/commons/releases
欢迎升级使用。
