### ISSUE TITLE
URL示例为死端口8080？可以和server.port同步吗？

### ISSUE THREAD

**Issue by yexuejc** [terran4j/commons#3]
![hp8 nrriacd2bth r jyp](https://user-images.githubusercontent.com/12441272/38078594-67de3a20-336f-11e8-9564-957babbbe79e.png)

**Comment by terran4j** [comment]
考虑到很多WEB服务前面有还有一层代理（如：Nginx ），用户访问的域名与端口与你在服务端配置的不一样，Api2Doc 提供了另一个解决方案：

在 application.yml 中配置 server.url , 如：
server:
  port:  8081
  url: http://doc.terran4j.com:9080

则文档中 URL 示例为：
http://doc.terran4j.com:9080/demo/user/123

也能解决你的问题，你试试看。

**Comment by yexuejc** [comment]
恩，我试试

**Comment by terran4j** [comment]
没问题吧？ 我 close 掉了哈。
